name: Test actions

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_REF