name: Test actions

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: echo $GITHUB_REF
    - name: set var
      run:
        if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          echo "anaconda-tag='dev'" >> $GITHUB_ENV;
        elif [[ $GITHUB_REF =~ refs/tags/* ]]; then 
          echo "anaconda-tag='main'" >> $GITHUB_ENV;
        fi
    - name: echo Anaconda tag
      run: echo ${{ env.anaconda-tag }}
